pipeline:
  build:
    image: node:8.11.3-alpine
    commands:
      - npm install
      - npm test
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: docker
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}
